version: "3.7"
secrets:
    # Secrets are single-line text files where the sole content is the secret
    portainer_admin_password:
        file: ./secrets/portainer/admin-password
services:
    proxy-manager:
        container_name: proxy-manager
        image: "jc21/nginx-proxy-manager:latest"
        restart: unless-stopped
        ports:
            - "80:80"
            - "81:81"
            - "443:443"
        volumes:
            - ./nginx-proxy-manager/development/data:/data
            - ./nginx-proxy-manager/development/letsencrypt:/etc/letsencrypt
            # - ./resolv.conf:/etc/resolv.conf
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        command: --admin-password-file '/run/secrets/portainer_admin_password' --logo 'https://static.creusent.com/img/logo/png'
        restart: unless-stopped
        dns:
            - 8.8.8.8
            - 4.2.2.2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer/development/data/:/data
            # - ./resolv.conf:/etc/resolv.conf
        secrets:
            - portainer_admin_password
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
networks:
    default:
        external:
            name: proxy-bridge
